# Generated by Django 5.2.4 on 2025-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultation",
            options={
                "ordering": ["start_datetime"],
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="date",
        ),
        migrations.AddField(
            model_name="consultation",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
